### ISSUE TITLE
Request for Missing File: 'sensor_placements.csv'

### ISSUE THREAD

**Issue by nkusyx** [canbatuhan/gp-mip#1]
I noticed that the file 'sensor_placements.csv' is missing. Could you please provide or upload this file? Thank you!

**Comment by canbatuhan** [comment]
@nkusyx 
Thanks for the heads up. This file had not been included in the repo, since it was a work of an on-going study within the same project, and at the time it was not published yet. As the paper has been published, I added the file `sensor_placement.csv` under the folder `/docs/input`.

Paper of the repository: https://www.researchgate.net/publication/369015878
Here is the paper about how the scores in `sensor_placement.csv` are calculated: https://ieeexplore.ieee.org/abstract/document/10210671

**Comment by canbatuhan** [comment]
Now I'm closing the issue.

**Comment by nkusyx** [comment]
Thank you for your prompt response and for adding the 'sensor_placement.csv' file to the repository. I appreciate your clarification regarding its absence initially due to the ongoing study.Once again, thank you for your assistance, and congratulations on the publication of your paper.
